### PR TITLE
Advanced sys def update

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-development-tools/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Adds the latest updates for the Advanced System API, from the original repository to the corresponding subtree of the NI CD Development Tools.

### Why should this Pull Request be merged?

Implemented CDS structures with OS === Win and OS === RT(Default) options for the commited VIs:
- advanced-sysdef-api/Source/_SubVIs/SysDef.Node.Info.Get.vi
- advanced-sysdef-api/Source/_SubVIs/TreeItem.Get.vi
- advanced-sysdef-api/Source/_SubVIs/TreeItem.Property.Get.vi
- advanced-sysdef-api/Source/_SubVIs/TreeItem.Property.Set.vi
- advanced-sysdef-api/Source/_SubVIs/_TreeItem.Property.Get.Dictionary.Info.vi
- advanced-sysdef-api/Source/_SubVIs/_TreeItem.Property.Get.Dictionary.Read.vi
- advanced-sysdef-api/Source/_SubVIs/_TreeItem.Property.Get.Dictionary.vi
- advanced-sysdef-api/Source/_SubVIs/_TreeItem.Property.Set.Dictionary.Info.vi
- advanced-sysdef-api/Source/_SubVIs/_TreeItem.Property.Set.Dictionary.Write.vi
- advanced-sysdef-api/Source/_SubVIs/_TreeItem.Property.Set.Dictionary.vi

The lack of CDS structures with these options was causing compile errors when building Engine libraries for Custom Devices for RT Targets. For some reason, due to cross-referencing, the Advanced System Definition API library and some of it's member VIs were included in the Engine builds for the RT targets, and this was leading to errors during builds, since .NET controls, used in this library are not supported on RT Targets.

### What testing has been done?

- Local manual testing has been done.

### CODE REVIEW

**Comment by buckd** [comment]
I'm not fully convinced this change is necessary. These VIs have been used for many years without issue, so I see two possible causes for your build failures.

1. Somehow, there is a reference to the VIs containing .NET references in the engine code. I suspect this is highly unlikely because the builds succeed on the build machines and only fail locally on your development machines (correct me if I'm wrong about that).
2. Much more likely is that LabVIEW is including edit-time dependencies in the source distributions that are being built on your local machine, but not on the build machine. This means App Builder is trying to include all the VIs necessary from advanced system definition library in the engine distribution, which is causing the failure. On the build machine (and on dev machines using the standard mobilize scripts), there is an INI key set that attempts to remove these edit-time dependencies. Please check your dev machine `LabVIEW.ini` file and look for **NI_AppBuilder_SDist_ExcludeEditTime = True**. If that key does not exist, add it and restart LabVIEW, then try to build.

If the INI key does not solve the problem and we do need to make this fix, I would like to see two changes.
- [ ] Any control or indicator that is not a .NET reference should not be contained within the conditional disable structure. As a general rule, front panel items, especially those on the connector pane, should not be in disable structures.
- [ ] In the RT cases, make sure to return an error on the wire that tells the user the VI is not supported on RT targets.

**Comment by DStavilaNI** [comment]
> 
> 
> I'm not fully convinced this change is necessary. These VIs have been used for many years without issue, so I see two possible causes for your build failures.
> 
>     1. Somehow, there is a reference to the VIs containing .NET references in the engine code. I suspect this is highly unlikely because the builds succeed on the build machines and only fail locally on your development machines (correct me if I'm wrong about that).
> 
>     2. Much more likely is that LabVIEW is including edit-time dependencies in the source distributions that are being built on your local machine, but not on the build machine. This means App Builder is trying to include all the VIs necessary from advanced system definition library in the engine distribution, which is causing the failure. On the build machine (and on dev machines using the standard mobilize scripts), there is an INI key set that attempts to remove these edit-time dependencies. Please check your dev machine `LabVIEW.ini` file and look for **NI_AppBuilder_SDist_ExcludeEditTime = True**. If that key does not exist, add it and restart LabVIEW, then try to build.
> 
> 
> If the INI key does not solve the problem and we do need to make this fix, I would like to see two changes.
> 
>     * [ ]  Any control or indicator that is not a .NET reference should not be contained within the conditional disable structure. As a general rule, front panel items, especially those on the connector pane, should not be in disable structures.
> 
>     * [ ]  In the RT cases, make sure to return an error on the wire that tells the user the VI is not supported on RT targets.

Hey Donovan, thank you for the feedback. Regarding the points you are making:

1. That much is obvious. As I mentioned during the previous meeting, I did some investigation regarding this behavior. In the case if this particular custom device, there is no direct reference from inside the Engine library. However, the Engine library references a Shared library, which in turn references the Advanced System Definition API. I believe that this is what's causing the inclusion. In the build spec for this project, the option for removing unused library members is checked, therefore, even if the Advanced System Definition is somehow referenced, it should be discarded during the build process, since its VIs are not actually used in the engine. Now, I mentioned that on some machines the build process is working and on some others it does not. The difference between the two is that in one case the Advanced System Definition API  is correctly filtered out, and in the other it is not.  Note: when I say "filtered", I mean that the Advanced System Definition API is still included in the build, however it's member VIs are discarded since those are not actually used. 
2. I tested the ini key you are suggesting - it does not work.   That being said, previously, the build was failing on both machines built with the mobilize script and VMs that I built manually ... 
As an opinion - I disagree with using this kind of tokens as workarounds, even if it mitigates some problem, simply because it does not actually solve the problem. This is a public facing API which is also referenced by CDs made open - other developers will download this API and they will do stuff with it ... and there is a big chance they will run into the same problems. The issue should be solved within the code itself. 
3. I am aware of this recommendation ... I think it comes from the fact that when you are using a Case structure or a CDS/DDS structure, the fact that you are including an indicator inside it, does not disable it. So, if that indicator is connected to the connector pane, and that subVI is executed inside another VI, most likely you will get some default value for that particular output. Since we cannot know the default value that was set for that indicator (if it was set), this can lead to some uncertainty. From what I know, placing the indicator inside the CDS however, does not break the code or the flow in any way.  Is it any particular reason why you would like to do so ? (some documentation would be nice - I did some checks online, but I did not find anything specific on this). These VIs are not supposed to be executed in the first place on the RT. 

4. Regarding returning the error - this seems like a good idea. I will consider adding this.

**Comment by buckd** [comment]
I can build Instrument Addon for all targets on my machine with the LV 2020 f1 patch and all latest dependencies with no alterations to any of the code. Can you provide the versions you have of the dependencies listed in the [Instrument Addon Readme](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/main/README.md)? It may be you just have an older version of dependencies.

>    As an opinion - I disagree with using this kind of tokens as workarounds, even if it mitigates some problem, simply because it does not actually solve the problem. This is a public facing API which is also referenced by CDs made open - other developers will download this API and they will do stuff with it ... and there is a big chance they will run into the same problems. The issue should be solved within the code itself.

This token was added specifically to solve problems like this (it was created specifically for VeriStand custom device builds). It is documented in our [READMEs](https://github.com/ni/niveristand-engine-simulation-toolkit-custom-device/blob/main/README.md) when required to build.

I would argue that this change is more of a workaround. Disabling code that doesn't work on some targets simply because LabVIEW is not doing what you think it should is the definition of a workaround. In this case, the better option is letting LabVIEW do the correct thing for you by setting the correct token.

Again, without being able to reproduce a failing build locally or on the build machine, this points me to something different with your machine setup and I am hesitant to submit this change without knowing why it is different across machines. I would like to know more about the machines that have failing builds instead of blindly putting in this code just because it seems to fix something that doesn't appear broken to me.

**Comment by DStavilaNI** [comment]
> 
> 
> I can build Instrument Addon for all targets on my machine with the LV 2020 f1 patch and all latest dependencies with no alterations to any of the code. Can you provide the versions you have of the dependencies listed in the [Instrument Addon Readme](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/main/README.md)? It may be you just have an older version of dependencies.
> 
> > As an opinion - I disagree with using this kind of tokens as workarounds, even if it mitigates some problem, simply because it does not actually solve the problem. This is a public facing API which is also referenced by CDs made open - other developers will download this API and they will do stuff with it ... and there is a big chance they will run into the same problems. The issue should be solved within the code itself.
> 
> This token was added specifically to solve problems like this (it was created specifically for VeriStand custom device builds). It is documented in our [READMEs](https://github.com/ni/niveristand-engine-simulation-toolkit-custom-device/blob/main/README.md) when required to build.
> 
> I would argue that this change is more of a workaround. Disabling code that doesn't work on some targets simply because LabVIEW is not doing what you think it should is the definition of a workaround. In this case, the better option is letting LabVIEW do the correct thing for you by setting the correct token.
> 
> Again, without being able to reproduce a failing build locally or on the build machine, this points me to something different with your machine setup and I am hesitant to submit this change without knowing why it is different across machines. I would like to know more about the machines that have failing builds instead of blindly putting in this code just because it seems to fix something that doesn't appear broken to me.

We are doing the dev in LV2018, since per specification it has to be the earliest supported version. I don't think it's a dependency problem, at least not from the other packages - in my opinion, the problem is strictly related to the Advanced System Definition API. As such, you can use the latest versions of the packages listed in the readme file, as long as you have the Advanced System Definition API without the fix. If you want to attempt to reproduce it, you only need to setup a VM with VS+LV2018 and dependencies on it. Alternatively, I can give you access to my LV2018 VM ... even though I have already the updated API in place there, you should be able to see the problem I am referring to (Advanced SysDef API is included in the build).

Regarding the fix itself - first of all, as I mentioned, the token does not work (at least not for me). Then, to elaborate a little bit (and at this point this would be a more high-level discussion), a "workaround" is for me something that does not fix the specific issue in the problematic code. The token, from this perspective is something that ought to make LabVIEW and the project work with the faulty code and it's not normally there, installed by default. The CDS approach, by contrast, fixes the problem with the code itself, since it was never intended to run on RT targets in the first place - essentially, it enforces this (intended) behavior.

**Comment by buckd** [comment]
The reason `Advanced System Definition.lvlib` is listed as a dependency is due to `Instrument Addon Shared.lvib:Protocol FG.vi` being called in `Initialize Instruments Refs.vi`. `Protocol FG.vi` calls the Property get/set VIs from the advanced sysdef API, so there is definitely a dependency there. This is the underlying cause of the failure. Engine code should never be called offline, which means there should be no reason to call into this API here. Resolving this unnecessary dependency should make any build failure related to this .NET references in this library go away.

I was unable to reproduce the build failure in 2018 on my machine. However, @Karl-G1 was able to reproduce what we think is the same failure on a brand new 2018-only machine. We set the INI token and the build succeeded, so I stand by my original statement that setting your INI token should be the resolution in the case you choose to not remove the `Advanced System Definition.lvlib` dependency from the engine. Again, this token was intentionally added for the express purpose of building VeriStand custom devices. See Azure work item 726109. It is a build configuration option that simply is not exposed in the App Builder configuration page. This is not a workaround. This is a LabVIEW-supported option to build source distributions with the exact result that we want.

This is not a problem with the Advanced System Definition API. This is a problem with how the Advanced System API is being used. The dependency should be removed. In lieu of actually fixing this, the INI token should be used for local building.

**Comment by DStavilaNI** [comment]
> 
> 
> The reason `Advanced System Definition.lvlib` is listed as a dependency is due to `Instrument Addon Shared.lvib:Protocol FG.vi` being called in `Initialize Instruments Refs.vi`. `Protocol FG.vi` calls the Property get/set VIs from the advanced sysdef API, so there is definitely a dependency there. This is the underlying cause of the failure. Engine code should never be called offline, which means there should be no reason to call into this API here. Resolving this unnecessary dependency should make any build failure related to .NET references in this library go away.
> 
> I was unable to reproduce the build failure in 2018 on my machine. However, @Karl-G1 was able to reproduce what we think is the same failure on a brand new 2018-only machine. We set the INI token and the build succeeded, so I stand by my original statement that setting your INI token should be the resolution in the case you choose to not remove the `Advanced System Definition.lvlib` dependency from the engine. Again, this token was intentionally added for the express purpose of building VeriStand custom devices. See Azure work item 726109. It is a build configuration option that simply is not exposed in the App Builder configuration page. This is not a workaround. This is a LabVIEW-supported option to build source distributions with the exact result that we want.
> 
> This is not a problem with the Advanced System Definition API. This is a problem with how the Advanced System Definition API is being used. The dependency should be removed. In lieu of actually fixing this, the INI token should be used for local building.

Sure thing. In this case I do not think it makes sense to keep this PR open. Thanks for the input on this.

**Pull request closed without merging**
