### PR TITLE
Custom device serialization utilities

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-development-tools/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Create a new library for serializing and deserializing custom devices. This is intended as a replacement for the existing import/export utility, although as a reimagination of the library rather than a drop-in substitute.

The library builds and installs to vi.lib like other libraries in this repository, and includes a starting palette.

### Why should this Pull Request be merged?

We are exploring a more robust serialization and deserialization library. This is the first effort.

### What testing has been done?

Hand testing of the library in both online (in VeriStand) and offline (in LabVIEW) contexts.

### What work remains?

- No automated or manual tests are included. We need to determine how to test libraries in this repository.
- Error codes need to be updated to use the correct range.
- Probably more.

### CODE REVIEW

**Comment by rtzoeller** [comment]
@buckd previously we've had custom devices install error codes to `<Program Files>\National Instruments\Shared\LabVIEW Run-Time\<LabVIEW version>`, rather than `<Program Files>\National Instruments\Shared\Errors`, because the year-versioned path makes it easier to install one error file per package which removes the need for a common package.

It seems like there is an IDE-specific location, `<LabVIEW>\resource\errors`, which also can hold error files.

How do you feel about us installing the error file for this repository twice? Once to `<Program Files>\National Instruments\Shared\LabVIEW Run-Time\<LabVIEW version>`, to cover built applications, and once to `<LabVIEW>\resource\errors`, to cover the IDE use case? The alternative would be to create another package to install common error files to `<Program Files>\National Instruments\Shared\Errors`.

**Comment by buckd** [comment]
@rtzoeller I'm fine installing it to both locations.

**Review by buckd — APPROVED** [review]
- [ ] Does this give an error when closing if the ref is invalid?
image
- [ ] Can you put a note about why this only works in certain versions (and the earliest version where it shouldn't be broken)?
image

**Comment by rtzoeller** [comment]
>  Does this give an error when closing if the ref is invalid?

No.

>  Can you put a note about why this only works in certain versions (and the earliest version where it shouldn't be broken)?

Done.

**Pull request merged**
