### PR TITLE
Improve HTML Help Tool to automatically build the CHM file on the build machine

### PR DESCRIPTION
**Pull request by phutanu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-development-tools/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?
- Improves HTML Help Tool error reporting and added the use of relative path for Build CHM.cfg

### Why should this Pull Request be merged?
- Connects Error wire from cmd line call to report the error when the call was not successful (HTML Help workshop missing or other).
- Uses the path relative to the Build CHM.vi when no path is added in the Build CHM.cfg file.

### What testing has been done?
- Implementation tested on the local dev machine.

### CODE REVIEW

**Comment by phutanu** [comment]
> 1. Thanks for code cleanup that you did while modifying the VIs.
> 2. I like the default path behavior you added.
> 
> Question: When it comes to propagating the error from the system exec VI, have you confirmed that the information returned from the error is actually helpful? Or does it simply return that the system exec call couldn't get invoked? If the information really is worthwhile, then I'll approve that changes as well.

The issue that I had when building locally was that no error was returned by running the Build CHM.vi but no CHM was generated after that. This led to a somewhat lengthy investigation that would have not been needed if the CMD exe error wire would have been passed.

The error just states that the call was not successful and it will only be generated if the "HTML Help Workshop" is missing. ->This was the case for my initial setup.

Also this will also ensure that we have the latest changes on the build machine for the CHM file, and do not rely on developers to submit the correct and latest file.

**Comment by rtzoeller** [comment]
I haven't tested this assumption, but from looking at the code I believe the build will also fail if it can't find the help files, since we are now including the error output from the SysExec call. Is that the case?

This seems like it will break many of the custom device builds, since the path listed in the CHM configuration is relatively arbitrary (i.e. it matches some developer's local setup) and currently this error is being discarded. This isn't necessarily a problem, since it will force us to fix the configuration files, but it need to be called out in the PR description (including the subsequent merge commit).

**Comment by phutanu** [comment]
> I haven't tested this assumption, but from looking at the code I believe the build will also fail if it can't find the help files, since we are now including the error output from the SysExec call. Is that the case? Or does only the "return code" output get modified?
> 
> This seems like it will break many of the custom device builds, since the path listed in the CHM configuration is relatively arbitrary (i.e. it matches some developer's local setup) and currently this error is being discarded. This isn't necessarily a problem, since it will force us to fix the configuration files, but it need to be called out in the PR description (including the subsequent merge commit).

I tested this for the Instrument Addon repo and it does not break the build. The error will only be reported if you run manually "Build CHM.vi" or "LLB Pre-Build CHM Build.vi".

LLB Pre-Build CHM Build.vi

**Comment by rtzoeller** [comment]
> make an edit to the Wizard's scripting of the Build CHM.cfg file to prevent the Base Path from being set by default

I like this approach best.

**Comment by phutanu** [comment]
Hey Karl,

Thanks so much for taking the time to write that nice and very well explained feedback. I was aware of some implications, but not all of them, so I really appreciate you trying to help me understand this better.

I understand that this change will not propagate automatically to current custom devices.

> This benefit needs highlighted in the PR summary or title as it is the important part of the change.

Title adjusted.

> 1. make an edit to the [Wizard's scripting](https://github.com/ni/niveristand-custom-device-wizard/blob/master/ProjectTemplate/Source/NI%20VeriStand/Custom%20Device/NIVS_Consolidated_CDW_MetaDataObj/Custom%20Device%20CORE.vi) of the Build CHM.cfg file to prevent the Base Path from being set by default

Change implemented in [PR24 - Custom Device Wizard](https://github.com/ni/niveristand-custom-device-wizard/pull/24)

**Review by Karl-G1 — APPROVED** [review]

**Review by niphilj — APPROVED** [review]

**Pull request merged**
